### ISSUE TITLE
你好，想问下你博客里说到的几本书是哪个出版社的呀？好多同名的

### ISSUE THREAD

**Issue by luffluo** [huanghantao/huanghantao.github.io#1]
[2017暑假学习总结](https://huanghantao.github.io/2017/08/28/2017%E6%9A%91%E5%81%87%E5%AD%A6%E4%B9%A0%E6%80%BB%E7%BB%93/)
这本书《Linux网络编程》一搜好多
剩下的书，方便的话，可不可以贴个图 :)

**Comment by huanghantao** [comment]
不推荐那本了，推荐这个：https://book.douban.com/subject/1500149/

**Comment by luffluo** [comment]
> 不推荐那本了，推荐这个：https://book.douban.com/subject/1500149/

好的，谢谢

**Comment by huanghantao** [comment]
> > 不推荐那本了，推荐这个：https://book.douban.com/subject/1500149/
> 
> 好的，谢谢

如果对`Swoole`项目感兴趣的话，可以加一个微信codinghuang
