### ISSUE TITLE
正式回应前女友对我的污蔑

### ISSUE THREAD

**Issue by huanghantao** [huanghantao/huanghantao.github.io#41]
> 想想之前相处的事情就很气，只站在父母这边，和父母出现重大利益冲突时，只会心疼他爸妈，要求我要孝顺，这不是妈宝是什么，我给你做饭，你不喜欢的就不吃，你妈做的，不好吃我也不能浪费，之前的那个臭笋鸭，双标
  人生规划也是，只跟父母先沟通，然后再要求我去考公，我已经表现出明显的抗拒了，只强调我没对你妈表现出尊敬，这点我确实没做好，但你有尊重我的想法吗
  订婚也是，我如果不要求买房，那一起买也成，你嫌我工资比你低，就不买这么大的，旧一点的，如果没必要，我也不会说要买，我也不想增加我们以后的经济负担，你以为你之前做的那些事情，以及你爸妈疯狂问你要钱做这做那，买房在他们自己名下，问你要钱资助买店铺，各种生活上的支出，名义上都是孝顺，为你减轻养老负担，一边标榜自己有养老工资，一边说给你减轻压力，等到我们订婚时，他们说要他们支出，就要听他们的，你自己也深刻认同，资产的积累都在他们手上，你确定你爸妈日后不会打苦情戏说，经济上给你规划了这么多，还如何如何吗，可能你压根不在乎我，牺牲我的意志，满足你跟你爸妈的想法就好了
   你做那些事情，伤害我的同时，要降彩礼，不降就是不爱你，花这些彩礼不如去娶个新的年轻的，我们不是从年少走来的吗，以后你如果真的发达了，你确定你不会拿这个压制，要我做出其他的牺牲吗
    当我委屈自己的感受，为关系做出让步的时候，你说要一人一半，我不愿意，而后，我再次退让，你说真爱就不应该有彩礼，像极了今日割一城，明日割十城，得寸进尺，你压根不是想促成事情的
     当你拿出成本论，说相处五年，之前付出了这么多，还要彩礼时，确实你有付出，请问，相处我没有付出吗，如果我没有付出，你后面何来的对我只有愧疚这句话，你的付出是有成本计算的，不然后面不会拿出来说事
     金钱上你确实付出比我更多，其他呢，这如何比呢，要罗列吗，要全部转换成你在意的金钱计算吗，在一起这么多年，我有超前消费吗，有让你付出大部分身家给我买礼物吗，我们大部分时候是讨论如何更经济生活吧，尽量做饭，减少打车，而后生活习惯两人部分融合了
      我要感念你的付出，我确实感念了，也做出了让步，可你如何对我，计较没有立即答应，没有主动，我为了商谈彩礼不出现差池，各方面打听当地同龄人的做法的时候，这不是努力是什么，你如何自证你对我的爱：答应我订婚的事情，然后说出上面的那些“商量“话，威胁我不降就退婚，你不要再跟你爸妈交流了，问题不是出现在你就是你爸妈
        我的朋友们，也是女方说要不就订婚吧，一切小情侣就自己搞定了，父母并没有因为资助而插手
       可能你对我没几分爱，嫌弃我不如你工资或者不是体制内，五年时间呢，在一起的时候我们旗鼓相当吧，可能你更加自我了，更加注重经济价值了，你没有摆在平等的位置选择跟我一起努力，如果是社会人士，我确实应该用这种思维处事，用在家庭和伴侣上未免太过势利了吧，人都有事业上不如意的那天（事实证明我事业未必不如意），那时候你要我如何对你
       以上如果不是如今的我更加沉着理性，你当初那些说法和做法对我的打击是致命的，说是PUA也不为过，你也看到了，我找你的时候，你把我关在门外站了一下午，你睡醒了才给我开门，我抱着你哭，一晚上都在念叨不要离开我，我出现了过度讨好，过度自卑，过度缺乏安全感，愤怒，怨恨，愧疚交杂的情绪，失眠对我来说也是家常便饭，相信这一切你也看到了，当我为我年少不经事做的不足的地方道歉时，我却等不到你因为你做的不对的事情的道歉，只有你高高在上的审视，如果我改进不到位，随时把我拉黑删除
         如果你听你妈妈说我们不合适，为何相处五年才说，我刚在一起几个月的时候我曾经说过我们有很大不同，我喜热闹，你喜安静，我喜运动，你喜游戏，我擅长语言表达，你经常沉默，我爱好广泛但不精，你只专注于一件事，我注重生活，我喜欢自己捣鼓吃食，不喜欢外卖，我喜欢把事情立马做完，你经常拖延，但你当时却说你觉得挺合适，我那时候想着不好的缺点可以督促改掉，有些的地方可以互补，正是因为不同才互相吸引
          所以问题出在哪，相处策略出了问题，你过度自我，根本不是一言蔽之的不合适
          其实你真的挺妈宝，最后问题基本都出在你身上，你却把问题都推给了我，最后共同问题的分析解决也由我一人承担，中间情绪上的起伏，你只有评判和逃避，到底谁爱的深沉，谁真正缺乏责任心，只追求轻松快乐，迄今为止一目了然了吧

我来给你捋一捋时间线以及你省略的种种细节：

去年寒假，你提出让我来订婚，要10w订金。我没有犹豫，当天准备钱，后天就过去了付钱。付完订金后，我私下问你这剩下的20w彩礼能不能少点，你说你爸妈不让少。我说那你给我垫一点，你不愿意。我比较震惊，内心想原来你更看重钱而不是感情。

> 人生规划也是，只跟父母先沟通，然后再要求我去考公，我已经表现出明显的抗拒了，只强调我没对你妈表现出尊敬，这点我确实没做好，但你有尊重我的想法吗

我来说一说这里的“明显抗拒”指的是什么，在我母亲的面前对着我的鞋子一直吐瓜子壳，掐我大腿。我并没有要求你要考公，只是建议你考公。因为我了解你，你本来就不是做程序员的料，回家也不学习，基础差，有一个铁饭碗对你和我好处都更大。

>  订婚也是，我如果不要求买房，那一起买也成，你嫌我工资比你低，就不买这么大的，旧一点的，如果没必要，我也不会说要买，我也不想增加我们以后的经济负担，你以为你之前做的那些事情，以及你爸妈疯狂问你要钱做这做那，买房在他们自己名下，问你要钱资助买店铺，各种生活上的支出，名义上都是孝顺，为你减轻养老负担，一边标榜自己有养老工资，一边说给你减轻压力，等到我们订婚时，他们说要他们支出，就要听他们的，你自己也深刻认同，资产的积累都在他们手上，你确定你爸妈日后不会打苦情戏说，经济上给你规划了这么多，还如何如何吗，可能你压根不在乎我，牺牲我的意志，满足你跟你爸妈的想法就好了

付完订金后，**你可不是说不要房子**（你不要房子是因为我后面提出不结婚了，你才不得已说不要房子了，你什么都不要了）。我说我们国庆结婚吧，你说太早了，你要我买房子，你不喜欢我父母买的房子（我父母买的房子，确实有不足，买的期房，运气不好，差点烂尾，但是最终成功交房了），你要五金，你要砖戒。**你说我父母买房在他们名下**，这有问题吗？我父母买房的时候，我还在读大学，我父母没告诉我他们在市区买了房子。其实我也并不关心这套房子，我也不关心我父母有多少钱，我有能力自己买房子，你父母为什么不给你买房子在你名下呢？
我母亲问我要钱买店铺，这有问题吗？那时候我们也还没有结婚的计划，况且，这个店铺是在我名下，40w。你为什么老是对这个店铺过意不去。我多次说这是底线，你不要一直提这个店铺的事情，没办法，你一直提，好，你拎不清轻重，那我选择分手。
“爸妈疯狂问你要钱做这做那，各种生活上的支出”，我在外面打工，我平时给我父母一些零碎的钱作为回报有问题吗？你平时难道不给你父母钱吗？
我父母不会对我唱苦情戏，我父母很爱我。彩礼钱他们愿意付，觉得剩下的20w也不多。是我个人提出希望你垫一点，也就2、3w这种，我就是想看看我在你心中的分量（如果你毫不犹豫的说，可以啊，那么我很认可你是我的妻子。但是你的犹豫，让我看到了你的态度。就好比你们女方常说的彩礼只是一个态度。但是我想说，彩礼何尝又不是代表女方自身的态度呢？）。这是应该是你当时唯一有机会“牺牲”的时候，你不愿意。（这里，我补充一点，你有一个弟弟，你一直污蔑我说我妈宝男，我能说你是伏弟魔吗？）
你老是说我父母不好，你的九价疫苗是我母亲托关系帮你打的？要不然都快到时间了吧？可你父亲是怎么对我的？我问你父亲有无嫁妆返回？你父亲说看人？？？怎么？你父亲觉得我人品有问题吗？你父亲说没钱就好好努力去赚钱。我就想问，你父亲有什么资格对我说这句话，他没有稳定的工作，对着工资比他高好几倍的人说这样的话？

> 你做那些事情，伤害我的同时，要降彩礼，不降就是不爱你，花这些彩礼不如去娶个新的年轻的，我们不是从年少走来的吗，以后你如果真的发达了，你确定你不会拿这个压制，要我做出其他的牺牲吗

到这里，你难道还不明白为什么我不想和你结婚了吗？我很看中女方是否真的爱我，爱我会体现在生活的点点滴滴上面。对我和其他男生会有明显的区别。你常说你在昆山为我做饭，但是，实际上这顿饭你自己不吃吗？你有做过我喜欢吃的菜吗？我们只不过是各自做着各自喜欢吃的菜，分享给对方而已。我父母怎么做的呢？每次我回家，怕我饿着，特意回家做饭，做完后接着回去上班。想想我是怎么对你的，我们从大三开始就异地，工作后的2、3年也异地。我是不是每个月甚至20天左右就去你那里一趟，无论多远，从上海到深圳、北京到深圳、昆山到深圳，疫情期间也跑过去。我有一句抱怨吗？难道我是要出差顺便看你吗？哪一次去你那里不是周五下班后赶车，周末晚上在火车上度过，周一早上继续回到工作岗位。我都为我这五年的坚持感到不值。你坚持过什么？
当我意识到，我的付出和相亲女没啥区别的时候，正常人会怎么选择？相亲市场，我可以尽可能选择门当户对的人。也更加遵守“市场规则”，我表姐相亲结婚的，收到6、7w的订金后，订婚第二天就陪嫁了一辆车过去，也有一个还未结婚的哥哥。

> 当我委屈自己的感受，为关系做出让步的时候，你说要一人一半，我不愿意，而后，我再次退让，你说真爱就不应该有彩礼，像极了今日割一城，明日割十城，得寸进尺，你压根不是想促成事情的

我从未说过彩礼要一人一半。这是我不打算和你结婚后，你自己提出的，不要彩礼也是你说的。但是，当我看清楚了你之后，你说的这些又有什么意义了呢？

> 当你拿出成本论，说相处五年，之前付出了这么多，还要彩礼时，确实你有付出，请问，相处我没有付出吗，如果我没有付出，你后面何来的对我只有愧疚这句话，你的付出是有成本计算的，不然后面不会拿出来说事
     金钱上你确实付出比我更多，其他呢，这如何比呢，要罗列吗，要全部转换成你在意的金钱计算吗，在一起这么多年，我有超前消费吗，有让你付出大部分身家给我买礼物吗，我们大部分时候是讨论如何更经济生活吧，尽量做饭，减少打车，而后生活习惯两人部分融合了

你有算过我为了你花费的金钱吗？从你找实习开始，资助你每一场外地面试，虽然不多，可我也还在实习啊。把实习结束后存下的所有钱一次性去了海南旅游。每20天/一个月找你一次，每次大几百/1千块的路费你自己算吧，我自己都记不清了。平时过节时候发的小红包（你有给我主动发过吗？我给你发520，你给我发5.2我也没说什么），平时购物逛超市吃饭哪次买单的不是我。

> 我要感念你的付出，我确实感念了，也做出了让步，可你如何对我，计较没有立即答应，没有主动，我为了商谈彩礼不出现差池，各方面打听当地同龄人的做法的时候，这不是努力是什么，你如何自证你对我的爱：答应我订婚的事情，然后说出上面的那些“商量“话，威胁我不降就退婚，你不要再跟你爸妈交流了，问题不是出现在你就是你爸妈

是的，当地的订金确实是10w，彩礼20w，一分不差，谢谢你的努力。我从来没有威胁你不降就退婚，你理解为威胁，那是你自己的事情。我真的打算放弃结婚的原因我说过很多次了，就是不许再提及店铺的事情。我给过你很多次机会，你一次一次的触及我的底线。你那么在意的话，那你去找一个更有钱的吧。

> 以上如果不是如今的我更加沉着理性，你当初那些说法和做法对我的打击是致命的，说是PUA也不为过，你也看到了，我找你的时候，你把我关在门外站了一下午，你睡醒了才给我开门，我抱着你哭，一晚上都在念叨不要离开我，我出现了过度讨好，过度自卑，过度缺乏安全感，愤怒，怨恨，愧疚交杂的情绪，失眠对我来说也是家常便饭，相信这一切你也看到了，当我为我年少不经事做的不足的地方道歉时，我却等不到你因为你做的不对的事情的道歉，只有你高高在上的审视，如果我改进不到位，随时把我拉黑删除

我们已经分手了，你自己跑过来找我，我为什么要放你进来。就好比我们已经分手了，你赌气，要送我父母金项链和茅台。我让你别送你非要送（我父母压根就没拆开过）。好，送完后，后悔了，来找我折现，我给你转回了5000。有你这么作的吗？

> 如果你听你妈妈说我们不合适，为何相处五年才说，我刚在一起几个月的时候我曾经说过我们有很大不同，我喜热闹，你喜安静，我喜运动，你喜游戏，我擅长语言表达，你经常沉默，我爱好广泛但不精，你只专注于一件事，我注重生活，我喜欢自己捣鼓吃食，不喜欢外卖，我喜欢把事情立马做完，你经常拖延，但你当时却说你觉得挺合适，我那时候想着不好的缺点可以督促改掉，有些的地方可以互补，正是因为不同才互相吸引

错了，你是因为听了我在大学里面分享了“我是如何入职腾讯”的ppt之后，才找上我的。你非常喜欢对我们之间的感情加上很多修饰，实际上，你做的事情有没有用，是不是真心的，我能知道，不需要事后去修饰他们。你也非常喜欢把犯了错误后做的事情、道歉与你爱我混淆在一起，就好像你没有犯错前也是这般对我的，弄得好像把道歉做的事情是你平常做的事情一样。

我再来说一说我们分手后你这一年所谓的“坚持”。好听的和难听的话都被你说完了，一遍说着你会改，你什么都不要了，都是你自己的错，我没回你消息，你就不断地骚扰我，威胁我要去我家和公司门口贴横幅，骂我渣男。实际上，我会担心这些吗？首先，我朋友不多，屈指可数，出了你之外，我没有任何的女性朋友，我和你在一起，没有和其他任何女性私聊过。熟悉我的人也知道，我不喜欢交朋友，要么在睡觉，要么在写代码，要么在打游戏，没有任何可能出轨的机会。反倒是你，在我和你是男女朋友的期间，独自和其他男生约会，被他抱，我忍了；晚上和其他男生一块走路回去；跑去和其他的男生相亲。这些事情你自己品一品吧？

不多说了，这是我最后一次回应你。希望你能够知道为什么我们走不到最后。

**Comment by codingdeng** [comment]
我不知道该如何称呼你现在，但为了尊重你选择的距离，那我直呼你的名字吧，我并不想在公众场合拿来说这些事，但是由于我真的找不到你，邮件我也收不到已读的提醒，而你会经常上git，因此我选择了在这里发信息，起初可能是因为实在是委屈和想不通，后面看到你发的信息，我才知道，我们双方关注到的点，和产生的解读完全不同，这种差异性，本该在双方来往的沟通中消除，避免产生更大的误会，和吵架的升级
      接下来，我将回复你的消息，不是给其他人看的，而是跟你说；
      ----去年寒假，你提出让我来订婚，要10w订金。我没有犹豫，当天准备钱，后天就过去了付钱。付完订金后，我私下问你这剩下的20w彩礼能不能少点，你说你爸妈不让少。我说那你给我垫一点，你不愿意。我比较震惊，内心想原来你更看重钱而不是感情。----
      这个，如果你告诉我你没有犹豫，我会很感动，真的，但是当时吵架吵成了红包还要这么多，首先的不接纳，在给订金的时候，你都是站在爸妈身旁，而不是站在我身旁，但我们既然各有各的看法，那现在的我选择相信你，不因为其他，因为现在的我看待问题更加成熟了，如果各执己见，只是在诉说自己的苦衷，便没有了信任
     -------我来说一说这里的“明显抗拒”指的是什么，在我母亲的面前对着我的鞋子一直吐瓜子壳，掐我大腿。我并没有要求你要考公，只是建议你考公。因为我了解你，你本来就不是做程序员的料，回家也不学习，基础差，有一个铁饭碗对你和我好处都更大。--------你说你了解我，我会很感动，如果你将后面那句话改成，你兴趣面广，无法持续专注一件事情，可能和程序员的特质不太相符，为了我们双方的结构和未来更加稳定，也为了你能活得更加轻松，你可以考虑下考公，那么我会很乐意接受你的提议，因为我们都希望我们这个整体会越来越好，但没有人会希望被贬低，还能轻松地接受对方的提议，你或许可以客观地自我代入下，尤其是可能还跟自己的父母说过，当有人说你不行，不是这块料时，即使可能你有些说的是对的，你要我轻松愉快地接受，明星等公众人物都很难
      下面这些话比较多，我分块回应你
      ------付完订金后，你可不是说不要房子（你不要房子是因为我后面提出不结婚了，你才不得已说不要房子了，你什么都不要了）。我说我们国庆结婚吧，你说太早了，你要我买房子，你不喜欢我父母买的房子（我父母买的房子，确实有不足，买的期房，运气不好，差点烂尾，但是最终成功交房了），你要五金，你要砖戒。你说我父母买房在他们名下，这有问题吗？我父母买房的时候，我还在读大学，我父母没告诉我他们在市区买了房子。其实我也并不关心这套房子，我也不关心我父母有多少钱，我有能力自己买房子，你父母为什么不给你买房子在你名下呢？-------
      对的，你陈述的是事实，我一开始确实难以接受，买房子是因为我想要有一个两个人的窝，你不愿意觉得压力大，我们可以共同买，你觉得我回了赣州后工资比你低，那我们可以买小一点的，但是你觉得没必要，要买就买大的，大的住起来舒服，而且你说你不想压力这么大，压力大这回事，我起初并不认同，但后面看到你上班真的很辛苦，经常加班，各种，我心疼了，我开始觉得我是不是真的做错了，但也可能是我自作多情，因为我曾以为的很多你是为了我，你都否认了
      -------我母亲问我要钱买店铺，这有问题吗？那时候我们也还没有结婚的计划，况且，这个店铺是在我名下，40w。你为什么老是对这个店铺过意不去。我多次说这是底线，你不要一直提这个店铺的事情，没办法，你一直提，好，你拎不清轻重，那我选择分手。
“爸妈疯狂问你要钱做这做那，各种生活上的支出”，我在外面打工，我平时给我父母一些零碎的钱作为回报有问题吗？你平时难道不给你父母钱吗？-------
     这个我也曾经困惑过，因为我没听过父母问儿子一下要这么多买店铺的，尤其是当你拿这个说没钱了，要借钱结婚的时候，然后我们发生了后续一系列的争吵，首先希望你明白，买店铺的后果不应该由我承担，你不应该拿这个来说事，但我们结婚产生的共同债务和花费，我会一块承担；我赞成过时过节力所能及的情况下给老人买礼物，包红包，因为这样他们会很开心，这也是我们孝敬老人的一种体现，一直提是因为情绪没有被很好地承接
     -------我父母不会对我唱苦情戏，我父母很爱我。彩礼钱他们愿意付，觉得剩下的20w也不多。是我个人提出希望你垫一点，也就2、3w这种，我就是想看看我在你心中的分量（如果你毫不犹豫的说，可以啊，那么我很认可你是我的妻子。但是你的犹豫，让我看到了你的态度。就好比你们女方常说的彩礼只是一个态度。但是我想说，彩礼何尝又不是代表女方自身的态度呢？）。这是应该是你当时唯一有机会“牺牲”的时候，你不愿意。（这里，我补充一点，你有一个弟弟，你一直污蔑我说我妈宝男，我能说你是伏弟魔吗？）
你老是说我父母不好，你的九价疫苗是我母亲托关系帮你打的？要不然都快到时间了吧？可你父亲是怎么对我的？我问你父亲有无嫁妆返回？你父亲说看人？？？怎么？你父亲觉得我人品有问题吗？你父亲说没钱就好好努力去赚钱。我就想问，你父亲有什么资格对我说这句话，他没有稳定的工作，对着工资比他高好几倍的人说这样的话？--------
      这一个，我其实并没有感觉到他们愿意付欸，你跟我说10万的礼金是借的，对我还是很不满的态度欸，而且后面退婚后，你爸爸跟你说这一年没存到钱，而后你对我发脾气，觉得剩下的20不多，但是你好像对我发了很大脾气说要退婚欸，退婚后你才说花这些钱其实不多，但要花这些钱还不如娶一个更好的，啊，你不是希望我出一半，我不愿意，我说2：1，然后你不愿意了；唯一的，这个词真的很居高临下欸，我有个弟弟，但你也知道我平常对我弟弟的态度，我不会宠着他惯着他，我也这么对我爸妈说过
     我说你父母对你不好呢，是基于我认识的父母对子女做的事情，和你父母对你做的事情对比说的，其实我本不该说，因为我了解到的可能不是全貌，但是其实你可以耐心地跟我举例好好说说的你们家的相处习惯各种的，带我了解你们家
     拜托你妈妈给我约九价，这个我很感激，其实，所以我每次去，我都是带了礼物的，也包括那次在你们家做饭，那是第二次九价的时候
     -----可你父亲是怎么对我的？我问你父亲有无嫁妆返回？你父亲说看人？？？怎么？你父亲觉得我人品有问题吗？你父亲说没钱就好好努力去赚钱。我就想问，你父亲有什么资格对我说这句话，他没有稳定的工作，对着工资比他高好几倍的人说这样的话？------
     我爸爸说话是那样子，他对我们也是那样说话的，我不要求你去理解他，毕竟你们也没见几次面，你跟我说完之后，我也批评了他
    ------我很看中女方是否真的爱我，爱我会体现在生活的点点滴滴上面。对我和其他男生会有明显的区别。你常说你在昆山为我做饭，但是，实际上这顿饭你自己不吃吗？你有做过我喜欢吃的菜吗？我们只不过是各自做着各自喜欢吃的菜，分享给对方而已。我父母怎么做的呢？每次我回家，怕我饿着，特意回家做饭，做完后接着回去上班。想想我是怎么对你的，我们从大三开始就异地，工作后的2、3年也异地。我是不是每个月甚至20天左右就去你那里一趟，无论多远，从上海到深圳、北京到深圳、昆山到深圳，疫情期间也跑过去。我有一句抱怨吗？难道我是要出差顺便看你吗？哪一次去你那里不是周五下班后赶车，周末晚上在火车上度过，周一早上继续回到工作岗位。我都为我这五年的坚持感到不值。你坚持过什么？
当我意识到，我的付出和相亲女没啥区别的时候，正常人会怎么选择？相亲市场，我可以尽可能选择门当户对的人。也更加遵守“市场规则”，我表姐相亲结婚的，收到6、7w的订金后，订婚第二天就陪嫁了一辆车过去，也有一个还未结婚的哥哥。------
    看到这里的后面几句，我不是很想回其实，但我选择继续打起精神，昆山做的饭我会吃，我自己在宿舍是不太做饭的，但因为你也在，做饭是很好的选择，我做饭也会更加有动力，你也能少吃外卖和减肥，是对双方都好的选择，至于做的什么菜，我已经忘了，经常吃秋葵吧，秋葵是后期我实在是吃腻了的东西，我说如果再做秋葵，便你自己搞了吧，并没有对抗，是带有无奈，但随你喜好，你当时也很乐于倒腾，每次美滋滋地整辣椒炒肉，都会支开我，端上桌一起品尝，或嫌弃或夸奖，总归是甜地
    至于你说到的工作后的异地，首先我们是出于现实因素决定的，我的周一上班比你早些，赶回去待的时间就短了，我很感激你辛苦的来往，真的，每每想到这个确实感激，我也时常跟我爸妈提起这个，节假日稍长的时候，我会去上海找你，每每五一国庆会在你那度过，我快到站了，我后面再接着回复

**Comment by huanghantao** [comment]
> ```
> 我不知道该如何称呼你现在，但为了尊重你选择的距离，那我直呼你的名字吧，我并不想在公众场合拿来说这些事，但是由于我真的找不到你，邮件我也收不到已读的提醒，而你会经常上git，因此我选择了在这里发信息，起初可能是因为实在是委屈和想不通，后面看到你发的信息，我才知道，我们双方关注到的点，和产生的解读完全不同，这种差异性，本该在双方来往的沟通中消除，避免产生更大的误会，和吵架的升级
>   接下来，我将回复你的消息，不是给其他人看的，而是跟你说；
>   ----去年寒假，你提出让我来订婚，要10w订金。我没有犹豫，当天准备钱，后天就过去了付钱。付完订金后，我私下问你这剩下的20w彩礼能不能少点，你说你爸妈不让少。我说那你给我垫一点，你不愿意。我比较震惊，内心想原来你更看重钱而不是感情。----
>   这个，如果你告诉我你没有犹豫，我会很感动，真的，但是当时吵架吵成了红包还要这么多，首先的不接纳，在给订金的时候，你都是站在爸妈身旁，而不是站在我身旁，但我们既然各有各的看法，那现在的我选择相信你，不因为其他，因为现在的我看待问题更加成熟了，如果各执己见，只是在诉说自己的苦衷，便没有了信任
>  -------我来说一说这里的“明显抗拒”指的是什么，在我母亲的面前对着我的鞋子一直吐瓜子壳，掐我大腿。我并没有要求你要考公，只是建议你考公。因为我了解你，你本来就不是做程序员的料，回家也不学习，基础差，有一个铁饭碗对你和我好处都更大。--------你说你了解我，我会很感动，如果你将后面那句话改成，你兴趣面广，无法持续专注一件事情，可能和程序员的特质不太相符，为了我们双方的结构和未来更加稳定，也为了你能活得更加轻松，你可以考虑下考公，那么我会很乐意接受你的提议，因为我们都希望我们这个整体会越来越好，但没有人会希望被贬低，还能轻松地接受对方的提议，你或许可以客观地自我代入下，尤其是可能还跟自己的父母说过，当有人说你不行，不是这块料时，即使可能你有些说的是对的，你要我轻松愉快地接受，明星等公众人物都很难
>   下面这些话比较多，我分块回应你
>   ------付完订金后，你可不是说不要房子（你不要房子是因为我后面提出不结婚了，你才不得已说不要房子了，你什么都不要了）。我说我们国庆结婚吧，你说太早了，你要我买房子，你不喜欢我父母买的房子（我父母买的房子，确实有不足，买的期房，运气不好，差点烂尾，但是最终成功交房了），你要五金，你要砖戒。你说我父母买房在他们名下，这有问题吗？我父母买房的时候，我还在读大学，我父母没告诉我他们在市区买了房子。其实我也并不关心这套房子，我也不关心我父母有多少钱，我有能力自己买房子，你父母为什么不给你买房子在你名下呢？-------
>   对的，你陈述的是事实，我一开始确实难以接受，买房子是因为我想要有一个两个人的窝，你不愿意觉得压力大，我们可以共同买，你觉得我回了赣州后工资比你低，那我们可以买小一点的，但是你觉得没必要，要买就买大的，大的住起来舒服，而且你说你不想压力这么大，压力大这回事，我起初并不认同，但后面看到你上班真的很辛苦，经常加班，各种，我心疼了，我开始觉得我是不是真的做错了，但也可能是我自作多情，因为我曾以为的很多你是为了我，你都否认了
>   -------我母亲问我要钱买店铺，这有问题吗？那时候我们也还没有结婚的计划，况且，这个店铺是在我名下，40w。你为什么老是对这个店铺过意不去。我多次说这是底线，你不要一直提这个店铺的事情，没办法，你一直提，好，你拎不清轻重，那我选择分手。
> ```
> 
> “爸妈疯狂问你要钱做这做那，各种生活上的支出”，我在外面打工，我平时给我父母一些零碎的钱作为回报有问题吗？你平时难道不给你父母钱吗？------- 这个我也曾经困惑过，因为我没听过父母问儿子一下要这么多买店铺的，尤其是当你拿这个说没钱了，要借钱结婚的时候，然后我们发生了后续一系列的争吵，首先希望你明白，买店铺的后果不应该由我承担，你不应该拿这个来说事，但我们结婚产生的共同债务和花费，我会一块承担；我赞成过时过节力所能及的情况下给老人买礼物，包红包，因为这样他们会很开心，这也是我们孝敬老人的一种体现，一直提是因为情绪没有被很好地承接 -------我父母不会对我唱苦情戏，我父母很爱我。彩礼钱他们愿意付，觉得剩下的20w也不多。是我个人提出希望你垫一点，也就2、3w这种，我就是想看看我在你心中的分量（如果你毫不犹豫的说，可以啊，那么我很认可你是我的妻子。但是你的犹豫，让我看到了你的态度。就好比你们女方常说的彩礼只是一个态度。但是我想说，彩礼何尝又不是代表女方自身的态度呢？）。这是应该是你当时唯一有机会“牺牲”的时候，你不愿意。（这里，我补充一点，你有一个弟弟，你一直污蔑我说我妈宝男，我能说你是伏弟魔吗？） 你老是说我父母不好，你的九价疫苗是我母亲托关系帮你打的？要不然都快到时间了吧？可你父亲是怎么对我的？我问你父亲有无嫁妆返回？你父亲说看人？？？怎么？你父亲觉得我人品有问题吗？你父亲说没钱就好好努力去赚钱。我就想问，你父亲有什么资格对我说这句话，他没有稳定的工作，对着工资比他高好几倍的人说这样的话？-------- 这一个，我其实并没有感觉到他们愿意付欸，你跟我说10万的礼金是借的，对我还是很不满的态度欸，而且后面退婚后，你爸爸跟你说这一年没存到钱，而后你对我发脾气，觉得剩下的20不多，但是你好像对我发了很大脾气说要退婚欸，退婚后你才说花这些钱其实不多，但要花这些钱还不如娶一个更好的，啊，你不是希望我出一半，我不愿意，我说2：1，然后你不愿意了；唯一的，这个词真的很居高临下欸，我有个弟弟，但你也知道我平常对我弟弟的态度，我不会宠着他惯着他，我也这么对我爸妈说过 我说你父母对你不好呢，是基于我认识的父母对子女做的事情，和你父母对你做的事情对比说的，其实我本不该说，因为我了解到的可能不是全貌，但是其实你可以耐心地跟我举例好好说说的你们家的相处习惯各种的，带我了解你们家 拜托你妈妈给我约九价，这个我很感激，其实，所以我每次去，我都是带了礼物的，也包括那次在你们家做饭，那是第二次九价的时候 -----可你父亲是怎么对我的？我问你父亲有无嫁妆返回？你父亲说看人？？？怎么？你父亲觉得我人品有问题吗？你父亲说没钱就好好努力去赚钱。我就想问，你父亲有什么资格对我说这句话，他没有稳定的工作，对着工资比他高好几倍的人说这样的话？------ 我爸爸说话是那样子，他对我们也是那样说话的，我不要求你去理解他，毕竟你们也没见几次面，你跟我说完之后，我也批评了他 ------我很看中女方是否真的爱我，爱我会体现在生活的点点滴滴上面。对我和其他男生会有明显的区别。你常说你在昆山为我做饭，但是，实际上这顿饭你自己不吃吗？你有做过我喜欢吃的菜吗？我们只不过是各自做着各自喜欢吃的菜，分享给对方而已。我父母怎么做的呢？每次我回家，怕我饿着，特意回家做饭，做完后接着回去上班。想想我是怎么对你的，我们从大三开始就异地，工作后的2、3年也异地。我是不是每个月甚至20天左右就去你那里一趟，无论多远，从上海到深圳、北京到深圳、昆山到深圳，疫情期间也跑过去。我有一句抱怨吗？难道我是要出差顺便看你吗？哪一次去你那里不是周五下班后赶车，周末晚上在火车上度过，周一早上继续回到工作岗位。我都为我这五年的坚持感到不值。你坚持过什么？ 当我意识到，我的付出和相亲女没啥区别的时候，正常人会怎么选择？相亲市场，我可以尽可能选择门当户对的人。也更加遵守“市场规则”，我表姐相亲结婚的，收到6、7w的订金后，订婚第二天就陪嫁了一辆车过去，也有一个还未结婚的哥哥。------ 看到这里的后面几句，我不是很想回其实，但我选择继续打起精神，昆山做的饭我会吃，我自己在宿舍是不太做饭的，但因为你也在，做饭是很好的选择，我做饭也会更加有动力，你也能少吃外卖和减肥，是对双方都好的选择，至于做的什么菜，我已经忘了，经常吃秋葵吧，秋葵是后期我实在是吃腻了的东西，我说如果再做秋葵，便你自己搞了吧，并没有对抗，是带有无奈，但随你喜好，你当时也很乐于倒腾，每次美滋滋地整辣椒炒肉，都会支开我，端上桌一起品尝，或嫌弃或夸奖，总归是甜地 至于你说到的工作后的异地，首先我们是出于现实因素决定的，我的周一上班比你早些，赶回去待的时间就短了，我很感激你辛苦的来往，真的，每每想到这个确实感激，我也时常跟我爸妈提起这个，节假日稍长的时候，我会去上海找你，每每五一国庆会在你那度过，我快到站了，我后面再接着回复

> 我不知道该如何称呼你现在，但为了尊重你选择的距离，那我直呼你的名字吧，我并不想在公众场合拿来说这些事，但是由于我真的找不到你，邮件我也收不到已读的提醒，而你会经常上git，因此我选择了在这里发信息，起初可能是因为实在是委屈和想不通，后面看到你发的信息，我才知道，我们双方关注到的点，和产生的解读完全不同，这种差异性，本该在双方来往的沟通中消除，避免产生更大的误会，和吵架的升级

你回复我的漏洞我就不一一列举了，有时候判断一个人说的是否是真相，只需要看前后说话是否一致就行。你的回复看似很漂亮，可以让不明真相的人稍微同情你一点点，但是你可能自己都忘了你污蔑我的第一句话用词是什么了吧。这个“他”字是和我说的吗？你还敢说你是因为找不到我才在github上面发这些东西的吗？你除了在github上面做这些事情，分手后第一时间找我室友的女朋友以及你的朋友们说我是渣男。你看我有回应你吗？是不是抢占先机才能证明自己是无辜的？

> 想想之前相处的事情就很气，只站在父母这边，和父母出现重大利益冲突时，只会心疼**他**爸妈。

你的邮件我基本上都看了，其实你知道我有没有读你的邮件，因为你的每一封邮件基本上都会撤回，如果撤不回，那么代表已经读了，这也是我在网上查了之后才知道有这个操作的。我不希望你和你父亲一样是一个虚伪的人，诚实很重要。

不用多说了，好好过自己的日子吧，也求求你放过老实人吧。
